version: '3.8'

services:
  db:
    image: postgres:14
    container_name: delivery-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: delivery
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth_service:
    build:
      context: ./auth_service
    container_name: delivery-auth_service
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./auth_service:/app
    ports:
      - "8000:8000"
    env_file:
      - ./auth_service/.env
    depends_on:
      - db
  restaurants_service:
    build:
      context: ./restaurants_service
    container_name: delivery-restaurant_service
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8001"
    volumes:
      - ./restaurant_service:/app
    ports:
      - "8001:8001"
    env_file:
      - ./restaurants_service/.env
    depends_on:
      - db

  gateway:
    build:
      context: ./gateway
    container_name: delivery-gateway
    ports:
      - "80:80"
    depends_on:
      - auth_service

volumes:
  postgres_data:
